### ISSUE TITLE
RESTEasy 0031135: Class must be annotated with @Path exception in Mockito Unit Tests

### ISSUE THREAD

**Issue by nicolasduminil** [stephan-mueller/wildfly-showcase#1]
Hello,
This is not an issue but rather a question. I have cloned this repository, tested it and it worked as expected. However, using the sample project as a template for developing my own ones, I have the mentioned exception running a Mockito unit test, the equivalent of what you're doing in the GreetResourceTest class, when you invoke the resource, as follows:

    Response response = resource.greet("Stephan");

Of course, I have a different context, but everything is similar, in the sense that there is an API resource, injecting and invoking a service, etc. So I'm mocking these components in a similar way, for example:

      @Mock
      private Service service;
      @InjectMocks
      private Resource resource;

 I'm trying to call the API:

    Response response = resource.doSomething();

thinking that in the context of a unit test, with Mockito, this call doesn't require JAX-RS client, as this is the case in your project. However, the exception is raised, which doesn't happen when I run your project and, comparing both, I don't see significant differences of maven artifacts or anything else then just context.
Do you have an idea of why it happens in my case and not in yours ? Of course, I'm doing thae equivalent of what you're doing here:

    Mockito.lenient().doCallRealMethod().when(service).getMessage(Mockito.anyString());

Many thanks in advance for your help.

Kind regards,

Nicolas

**Comment by stephan-mueller** [comment]
Dear Nicolas,

thanks for asking. Can you provide the code (e.g. in a private repo if necessary) and a stacktrace to me? May be I can find the difference.

Best Regards
Stephan

**Comment by nicolasduminil** [comment]
Hi Stephan,

Many thanks for your reply. Finally, I managed to solve my issue.

The mentioned exception was caused by the REST endpoint which reads something like:

    @POST
    public Response createItem (Item item)
    {
      ...
      return Response.created(UriBuilder.fromResource(Item.class)
            .path("/items/{id}").build(id)).build();
    }

Here the UriBuilder.fromResource() method which is called is the real one, of course. And it tests whether the resource class is annotated with @Path. Which raises the exception 'cause, in test mode, annotations aren't visible. Hence, mocking UriBuilder such that to avoid this test, fixes my issue.

So, to resume, the idea was to modify the class under test such that to inject the UriBuilder and, in the unit test, to inject the mocked UriBuilder class. 

I would like to take advantage of this exchanges to tell you that your show case is great. And not only from the point of view of the Wildfly deployed micro-services, but also from the one of unit/integration/BDD testing, code quality coverage and others. Many thanks.

And while I'm at it, I would like to ask you whether you think that Wildfly might be a better micro-services platform than Quarkus ?

Kind regards,

Nicolas

**Comment by stephan-mueller** [comment]
Hi Nicolas,

good to hear that you found the problem. I already expected something like that. 

> I would like to take advantage of this exchanges to tell you that your show case is great. And not only from the point of view 
> of the Wildfly deployed micro-services, but also from the one of unit/integration/BDD testing, code quality coverage and 
> others. Many thanks.

You're welcome! I am always happy to help! My intention with the showcases is to provide an all encompassing solution to colleagues, customers and others on the same level as I would implement it for a real world application.

> And while I'm at it, I would like to ask you whether you think that Wildfly might be a better micro-services platform than
> Quarkus ?

In general I try to avoid answering these question, because there are often other reasons which affect the selection of the runtime environment. Anyway Quarkus is a great framework for developing micro-services but Quarkus takes it's own way in some cases (e.g. CDI Injection, Support für Enterprise Technologies like JSF or JMS Message Driven Beans). If you want or have to stay close to Jakarta EE and specifications like EJB, JMS or JSF Wildfly is still the right choice. It provides support Jakarta EE and MicroProfile and is able to integrate with other Enterprise technologies and frameworks like Camunda BPM. In addition to Quarkus and Wildfly there is a list of other micro service frameworks like Spring Boot (Pivotal), Helidon (Oracle) or Open Liberty (IBM) and many more (e.g. Micronaut, Vertx, ...). Which one of these fits best for you depends on many factors you may know best. In the end micro service architecture includes choosing the best solution (e.g. micro service framework) for each service individually it can result in using more than one or two, but does not mean to use all of them ;). 

I am currently working at a showcase (online-shop example) including Camunda BPM and two or three services. For the order-service which integrates Camunda BPM for the order process I have chosen wildfly and for the product catalog I chose Quarkus.

Best Regards
Stephan

**Comment by nicolasduminil** [comment]
Hi Stephan,

Thanks again for your reply. Yes, I fully agree that it's important to keep with Jakarta EE specs and, as a developer having used during decenies JBoss, WebLogic, WebSphere, etc. and others like Karaf, OSGi, I'm happy that the Microprofile is now supported as well by Wildfly. After having tested for a while Quarkus, I decided to stay with Wildfly. Open Liberty it's an interesting option as well. I'm not at all a fan of Spring Boot even if I have to use it as most of the projects I'm participating to require it.

What a coincidence that you're talking about Camunda ! Last week-end I was thinking to book some time in order to read their documentation and to perform some testings. I've been using during many years tools like Oracle SOA/BPM Suite, jBPM, Drools, Red Hat BPM Studio and others. I was deceived, like anybody I suppose, by the heavyness of these products and was thinking to give a try to Camunda, as it seems much more flexible. I'm glad to see that you have the same points of interest :-).

Kind regards,
Nicolas
